# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Test
  timeoutInMinutes: 0
  strategy:
    matrix:
      main:
      VM_ImageName: 'ubuntu-16.04'

pool:
  vmImage: $(VM_ImageName)

steps:
- checkout: self
  clean: boolean
  submodules: recursive

- script: |
    cd src/examples/docker/ubuntu/ && ./example_build.sh
  displayName: 'Docker Build'
